# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81209e9cd39a830e303b32d523ef8286ecc1738e4c8b1412d2132164943e3b835553edf5a0a8bb1b6e831a6f8968a342a8295e4d76b0d74b0454f9a04d32ecfc

test:
  secret_key_base: dca3f78eac55ab184732640c2a7fd6b06cb14cb8b163996ea5b72c2d3901d792d7b75eb338447ee703a9fe6117c5d81ad46c66589e2da2ede5029201b8bece2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
